// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZHoHi-lOfk2iH0YU15m5s3GcfRc7Kao',
    authDomain: 'learnix-chat.firebaseapp.com',
    projectId: 'learnix-chat',
    storageBucket: 'learnix-chat.firebasestorage.app',
    messagingSenderId: '867467617003',
    appId: '1:867467617003:web:4856c2d6b7adb8604c14ae',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnW7GNtDa5XmN_039JlBZplP0RZDj9WE0',
    projectId: 'learnix-chat',
    messagingSenderId: '867467617003',
    storageBucket: 'learnix-chat.firebasestorage.app',
    appId: '1:867467617003:android:1ef1ae2950ddf19e4c14ae',
  );
}
